### ISSUE TITLE
Home: Text change

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#1]
Current

It is a search engine that can be used for any kind of text data.
It sends server logs to Zinc and search for them or you can push
your application data and provide full text search.

Required

Zinc is a search engine that can be used for any kind of text data. It can be used for logs, metrics, events, and more. It allows you to do full text search among other things. e.g. Send server logs to ZincSearch and search for them, or you can push your application data and provide full text search or you can build a search bar in your application using ZincSearch.

**Comment by hengfeiyang** [comment]
i am thinking about we say we that:

```
Tired Of High Cost And Complexity Of Your Log Systems
```

but in the Features, we not provider something to support a better log solution.

**Comment by vp2890** [comment]
> Current
> 
> It is a search engine that can be used for any kind of text data. It sends server logs to Zinc and search for them or you can push your application data and provide full text search.
> 
> Required
> 
> Zinc is a search engine that can be used for any kind of text data. It can be used for logs, metrics, events, and more. It allows you to do full text search among other things. e.g. Send server logs to ZincSearch and search for them, or you can push your application data and provide full text search or you can build a search bar in your application using ZincSearch.


Fixed
