### ISSUE TITLE
Home: FAQ: Do we have SDK's available for Zinc?

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#13]
Current

Do we have SDK's available for ZincSearch?

Currently No. We are working towards making it available. You are recommended to use Zinc HTTP APIs for now.

Required

Do we have SDK's available for ZincSearch?

Currently No. We are working towards making the SDKs available. You are recommended to use ZincSearch REST APIs for now.

**Comment by vp2890** [comment]
Fixed
