### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#15]
Current

At ZincSearch, we bring Cloud, Kubernetes, DevOps and Engineering expertise to provide a solution to the problem of observability at low cost. ZincSearch is the simplest and easiest search system to get up and running. Founded in 2022 at ZincSearch we came up with an open source solution that provides and easy to use search engine that solves your observability needs best.

Required

At ZincSearch, we bring Cloud, Kubernetes, DevOps and Engineering expertise to provide a solution to the problem of observability at low cost. ZincSearch is the simplest and easiest search system to get up and running. Founded in 2022, at ZincSearch we came up with an open source solution that provides and easy to use search engine that solves your observability needs best.

**Comment by vp2890** [comment]
Fixed
