### ISSUE TITLE
About Us: Prabhat

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#21]
Current

Zinc was founded by Prabhat Sharma after years of his work at AWS working with hundreds of startups, ISVs and very large customers who face the challenge of searching logs and other application data.

Required

ZincSearch was founded by Prabhat Sharma based on his learnings from years of his work at AWS working with hundreds of startups, ISVs and very large customers who faced the challenge of searching logs and other application data.

**Comment by vp2890** [comment]
Fixed
