### ISSUE TITLE
About Us: Hengfei

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#22]
Current

Heingfei has previously served as a CTO at Xi'an Xinma Interactive Media & R&D Director at Beijing
CMS Top Technology. He is prolific Go and Javascript developer.

Required

Hengfei Yang is a full stack engineer with rich experience in distributed system development. He is passionate about open source. He has built and lead many technical teams in the past 10 years.

**Comment by vp2890** [comment]
Fixed
