### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#23]
Current

Almost every application requires search functionality. If you are using relational database for your application needs then using SQL LIKE for text searches has the potential to kill the database. Zinc is the perfect search solution in this case.

Required

Almost every application requires search functionality. If you are using relational database for your application needs then using SQL LIKE for text searches has the potential to kill the database. ZincSearch is the perfect search solution in this case.

**Comment by vp2890** [comment]
Fixed
