### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#29]
Docs

Remove Pro Vs Open Source
Browser fingerprinting
Incognito mode detection

**Comment by hengfeiyang** [comment]
about the url of `Get Started` is:

```
https://docs.zincsearch.com/02_getting-started/
```

i suggest rename to:

```
https://docs.zincsearch.com/getting_started/
```

i found many urls has a number prefix in url, it not a good idea.

**Comment by prabhatsharma** [comment]
Let's fix the renames later, after release

**Comment by vp2890** [comment]
> Docs
> 
> Remove Pro Vs Open Source Browser fingerprinting Incognito mode detection

Fixed
