### ISSUE TITLE
Home: Carousel

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#31]
Auto movement of carousel every 5 seconds

**Comment by hengfeiyang** [comment]
and the Screenshots of zinc should be update, we have autoUpdate now.

**Comment by prabhatsharma** [comment]
Latest screenshots can be picked up from:

Server	https://playground.dev.zincsearch.com/
User ID	admin
Password	Complexpass#123

**Comment by vp2890** [comment]
Auto Carousel Fixed
