### ISSUE TITLE
Home: Easy to Setup & Operate

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#6]
Current

It provides the most easy to get
started with logs.It has simple APIs
to interact and integrates with leading
log forwarders allowing you to get operational in minutes.

Required

ZincSearch provides the easiest way to get started with log capture, search and analysis. It has simple APIs to interact and integrates with leading log forwarders allowing you to get operational in minutes.

**Comment by vp2890** [comment]
Fixed
