### ISSUE TITLE
Home: FAQ - Can I replace elasticsearch with Zinc?

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch-website#9]
Current 

Can I replace elasticsearch with Zinc?

Zinc provides elasticsearch compatible ingestion APIs. So you can change the configuration (URL and authentication data) of your existing tools (fluent bit, vector, syslog-ng, etc) that are sending data to elasticsearch and it will start working right away. To view the data you will have to use either Zinc UI or Zinc APIs. Zinc currently does not provide an elasticsearch compatible query API, however we are working on making it compatible.

Required

Can I replace Elasticsearch with Zinc?

ZincSearch provides Elasticsearch compatible ingestion APIs. So you can change the configuration (URL and authentication data) of your existing tools (fluent bit, vector, syslog-ng, etc) that are sending data to Elasticsearch and it will start working right away. To view the data you will have to use either ZincSearch UI or ZincSearch APIs. Zinc currently does not provide an Elasticsearch compatible query API, however we are working towards making it compatible.

**Comment by vp2890** [comment]
Fixed

**Comment by vp2890** [comment]
I have updated few things here too, eg: Can I replace Elasticsearch with ZincSearch?
